ALTER TABLE `requests`
  CHANGE COLUMN `created_at` `created_at` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CHANGE COLUMN `started_at` `started_at` TIMESTAMP(6) NULL DEFAULT NULL,
  CHANGE COLUMN `finished_at` `finished_at` TIMESTAMP(6) NULL DEFAULT NULL;

ALTER TABLE `suspended_job_chains`
  CHANGE COLUMN `updated_at` `updated_at` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CHANGE COLUMN `suspended_at` `suspended_at` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);